<?php

function xmldb_assignsubmission_onlineviva_upgrade($oldversion) {
    global $DB;

    $dbman = $DB->get_manager();

    if ($oldversion < 2021052503) {
        // Code to add the column, generated by the 'View PHP Code' option of the XMLDB editor.'''
        $table = new xmldb_table('onlineviva_questions');
        $field = new xmldb_field('id', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, XMLDB_SEQUENCE, null, null);

        // Conditionally launch add field id.
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // Onlineviva savepoint reached.
        upgrade_plugin_savepoint(true, 2021052503, 'assignsubmission', 'onlineviva');
    }

    return true;
}
